# Generated by Django 5.0.1 on 2024-03-13 03:40

import APP.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', APP.models.CustomeUserManager()),
            ],
        ),
    ]
