# Generated by Django 5.0.1 on 2024-03-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer')], default='hombre', max_length=255),
        ),
    ]
